apiVersion: apps/v1
kind: Deployment
metadata:
  name: golist-frontend
  labels:
    app: golist-frontend
    tier: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golist-frontend
  template:
    metadata:
      labels:
        app: golist-frontend
    spec:
      containers:
        - name: golist-frontend
          image: saianilkumardeyyala/qod-web
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: GOLIST_API_URL
              value: "http://golist-api:8080"
